### ISSUE TITLE
With Atom 1.6.0, save positions cursor at end of file

### ISSUE THREAD

**Issue by atombender** [joefitzgerald/gofmt#1]
This is me hitting cmd-S and then moving the cursor up. Every time I hit cmd-S, the cursor moves to the end of the file.

![screen capture on 2016-03-17 at 20-05-20](https://cloud.githubusercontent.com/assets/50314/13864859/a48fd22c-ec7b-11e5-8cac-7c626c444aad.gif)

On larger files, the entire editor's syntax highlighting is disabled for a millisecond or so, indicating that the entire file has reloaded.

Of course, it's possible this isn't Atom 1.6.0, but some recent changes to this package. Both got upgraded at the same time.

Version 1.0.2, OS X.

**Comment by atombender** [comment]
Can confirm that it's happening with 1.5.3, too.

**Comment by joefitzgerald** [comment]
Sorry that this is happening. I haven't experienced this bug will try and reproduce as soon as possible. I'm fairly sure I know what the problem is.

**Comment by atombender** [comment]
Thanks!

**Comment by sunzl1989** [comment]
Same here. This is fairly annoying.

**Comment by joefitzgerald** [comment]
Please retest after updating to `gofmt` v1.0.3.

**Comment by atombender** [comment]
Fix confirmed.

**Comment by atombender** [comment]
...though I'm still seeing flickering. The entire file seems to be replaced every time I save, and reloaded, where there's a small delay before syntax highlighting is applied. I can confirm that this is not the case with `go-plus` 3.5 with its built-in format-on-save.

**Comment by dimfeld** [comment]
I'm still seeing the "cursor jumps to end" issue with 1.0.3 and Atom 1.6.0. It doesn't happen with all files though. I feel like there's correlation between file length and whether or not it occurs, but I haven't firmly established this. I have a feeling that atombender's comment above is the root issue though. If there's a way to get this back to the older go-plus behavior that would be great.

**Comment by joefitzgerald** [comment]
Please update to 1.0.4.

**Comment by dimfeld** [comment]
Much better. Thanks!

**Comment by atombender** [comment]
@joefitzgerald Thoughts on the flickering? I'm still on go-plus 3.5 because it's really annoying.

**Comment by atombender** [comment]
@joefitzgerald Never mind, I see that 1.0.4 addresses this. Thanks!
