### ISSUE TITLE
gofmt nor gometalinter do their job on test files

### ISSUE THREAD

**Issue by shadyyx** [joefitzgerald/gofmt#10]
Having a `package handlers` with `ABCHandler.go` filenames and their respective tests with `ABCHandler_test.go` which have `package handlers_test`, **gofmt** does not format code anymore and **gometalinter** does not point out to errors in code anymore (claiming "No issues" at the bottom of the editor).

If I remove the `_test` part from the package name in `_test.go` file, suddenly, both **gofmt** and **gometalinter** work...

I didn't find any setting to suppress such (IMHO) invalid behavior.

**Comment by joefitzgerald** [comment]
It's likely due to a compilation or syntax error; gofmt is not showing the errors, but I'm working on https://github.com/joefitzgerald/builder-go right now to surface this information in the way go-plus used to in 3.5.x. See also https://github.com/joefitzgerald/go-plus/issues/403.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. [`builder-go`](https://atom.io/packages/builder-go) will now try to compile your source (test or otherwise) and report errors that would prevent formatting from occurring.
