### ISSUE TITLE
goimports & gofmt not working

### ISSUE THREAD

**Issue by dewey4iv** [joefitzgerald/gofmt#15]
atom versions: 1.6 & 1.6.2
go-plus version: 4.1.0
gofmt version: 1.1.5

Saving the file doesn't run goimports. I've check that it is selected in the settings: `goimports` -- anywhere else I can check?

**Comment by dfreire** [comment]
atom 1.6.2
go-plus 4.1.0
gofmt 1.1.5

Setting the format tool to `gofmt` works for me, but setting it to `goimports` doesn't work.

**Comment by dewey4iv** [comment]
Setting to the `goreturns` works for me -- seems like the `goimports` is the only one that doesn't function properly. I'm starting to think that the problem is actually w/ goimports instead -- not sure though.

**Comment by dfreire** [comment]
Not likely... **goimports** works fine for me in the command line.

**Comment by dewey4iv** [comment]
Sorry should have clarified: `goimports` + `gofmt` doesn't seem to be working properly. I'm thinking that `goimports` might have caused a breaking change.

**Comment by joefitzgerald** [comment]
Are you open to a screen sharing session to figure this out? If so, please join the `#go-plus` channel in one of these Slack teams, and then direct message me your email address:

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by dewey4iv** [comment]
Looks like it was because I was on an older version of `goimports` -- thanks for the help!

**Comment by joefitzgerald** [comment]
We have a fix! Run: `go get -u golang.org/x/tools/cmd/goimports`

**Comment by dfreire** [comment]
Confirmed, sorry for the trouble.
