### ISSUE TITLE
goimports adding not wanted imports

### ISSUE THREAD

**Issue by gempir** [joefitzgerald/gofmt#18]
I use a log library which I import in main.go and only there and make a global variable log

Everytime I try to save in another file it will import another logger, but it's totally irrelevant and even spits out and error that log is already declared.

Would be nice to be able to just turn off the executing of goimports or whatever is causing this.

**Comment by joefitzgerald** [comment]
Please file an issue at https://github.com/golang/tools

**Comment by joefitzgerald** [comment]
Well that was a bit cruel; they've disabled github issues on that repo. Essentially, this is a goimports issue. You have three options:
1. Find a place to log an issue with goimports directly
2. Actually patch the issue in goimports and contribute it back
3. Stop using goimports

**Comment by fjorgemota** [comment]
Seems like goimports issues are being added to golang/go repository. See [this list](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+goimports+).
