### ISSUE TITLE
gofmt is formatting .yml files

### ISSUE THREAD

**Issue by campbel** [joefitzgerald/gofmt#2]
Using 
atom 1.6.0
gofmt 1.0.2
go 1.5.1
windows 10

I have a .yml file in my project and upon saving with the gofmt atom plugin running the file loses all indentation, all spaces are turned to new lines and the cursor is moved to the end of the file.

**Comment by wyattjoh** [comment]
Same issue with me but for `.env` files. Disabling the plugin does resolve the formatting issues.

**Comment by joefitzgerald** [comment]
Please retest after updating go `gofmt` v1.0.3.

**Comment by campbel** [comment]
Can't test on the same machine as last night, but my other machine is working fine with the new update. Thanks for the quick turnaround!
