### ISSUE TITLE
goimports does not prioritize existing imports

### ISSUE THREAD

**Issue by calvn** [joefitzgerald/gofmt#20]
I am not sure if this is the right place to report the issue, but I figured you could point me to the right direction if not. Currently goimports will automatically determine the missing imports based on the package name, but does not consider my currently imports from other files from the same project.

For example, if I am using `github.com/Sirupsen/logrus` and importing it under `log` (i.e. `import log "github.com/Sirupsen/logrus"`), the next time I use methods from the log package, goimports will import `github.com/apex/log` instead.

Would it be possible for this package to bypass the issue by trying to fill in the missing imports from existing imports used in the project before calling goimports to fetch them?

**Comment by joefitzgerald** [comment]
Your issue is upstream. This is a goimports issue, please file it there.
