### ISSUE TITLE
goimports no longer works after update

### ISSUE THREAD

**Issue by tj** [joefitzgerald/gofmt#22]
Just updated via go-plus, and still have goimports selected (and it's installed).

The rest of the stuff in go-plus that upgrade is awesome though thanks! seems a lot snappier as well

**Comment by joefitzgerald** [comment]
Hey @tj, are you open to a screenhero pairing session so I can observe the issue? If so, DM me on Slack (gophers.slack.com or atomio.slack.com) and we can exchange email addresses.

**Comment by dcormier** [comment]
I also had this start failing at some point between yesterday and today (though I didn't have an update to this package in that time).

When looking at the IDE,  When looking at the console in the dev tools, the errors end up there.

![gofmt](https://cloud.githubusercontent.com/assets/216265/15517873/14cd4f70-21c8-11e6-883f-9e37543e28b2.png)

Confoundingly, it works fine if I create a new file outside my project to try to reproduce with a simple scenario. I haven't yet had a chance to dig in further.

**Comment by kcoleman731** [comment]
@joefitzgerald Having the same issue over here. Will ping you on slack.

**Comment by tj** [comment]
hey sorry for the delay! I just completely removed the tools repo from my GOPATH and re-installed, appears to be working again sorry for the noise.

Thanks again for the great plugin!

**Comment by joefitzgerald** [comment]
For others wondering how to do this:
- `rm -rf $GOPATH/src/golang.org/x/tools`
- `rm -rf $GOPATH/bin/goimports`

Then quit and relaunch atom. `gofmt` will prompt you to `go get` goimports.

**Comment by pwaller** [comment]
@joefitzgerald I just did an update and goimports stopped working in the editor on save. It works fine at the command line (with `goimports -srcdir $PWD < file.go`). I'm running the latest version of goimports, which is [a2a5522](https://github.com/golang/tools/commit/a2a552218a0e22e6fb22469f49ef371b492f6178). I followed your instructions to delete `x/tools` quit and relaunch atom with no luck. I've reinstalled it and relaunched and it still doesn't work. Any ideas?

**Comment by pwaller** [comment]
Found the reason. I have broken symlinks in my path and goimports now reads symlinks, reporting the errors to stderr. `gofmt` appears to not format the output if stderr is present, even if the result is actually formatted. Nor does it indicate that there is a problem, it just fails to work.

I guess goimports reporting errors on the symlink is probably a goimports bug.

**Comment by joefitzgerald** [comment]
@pwaller can you please provide sample output from stdout/stderr when experiencing the issue? With that, I will try to repro locally and handle more gracefully.

**Comment by pwaller** [comment]
It looks like this, but with hundreds of errors (errors not separated with a newline).

```
lstat /home/foo: no such file or directorylstat /home/foo: no such file or directory
```

**Comment by pwaller** [comment]
Update: https://github.com/golang/tools/commit/e047ae774b027ae958a270598c5ac2591e457afc fixed the problem.
