### ISSUE TITLE
how can I use both gofmt and goimports

### ISSUE THREAD

**Issue by simon-xia** [joefitzgerald/gofmt#25]
why not use selected config like
- goimports
- goreturns
- gofmt

so we can choose some of them instead of only one

**Comment by joefitzgerald** [comment]
It would be redundant to use more than one. You can choose from those three options for the default tool to be used on save. You can also individually run any of them via the command palette (type `go: gofmt` / `go: goimports` / `go: goreturns`) and you can disable format on save.
- gofmt does what gofmt does
- goimports does what gofmt does plus adds / removes imports 
- goreturns does what goimports does plus adds return statements
