### ISSUE TITLE
Where are deps installed / downloaded to?

### ISSUE THREAD

**Issue by ghost** [joefitzgerald/gofmt#26]
Hi. I tried to find the path where deps are installed or downloaded to, but no luck. Can you point me in the right direction?

**Comment by joefitzgerald** [comment]
> The deps

Do you mean the tools that go-plus and related packaged download to make use of? All that is run is `go get -u <package path>`, so that would imply the source is at `$GOPATH/src/<package path>` and the binaries are at `$GOPATH/bin`.

**Comment by ghost** [comment]
Thanks. Okay, I see. The plugin actually uses the `go` tool in the background, so it's as if I had `go get xxx` myself.
