### ISSUE TITLE
Syntax highlighted code blinking for files exceeding viewport

### ISSUE THREAD

**Issue by celrenheit** [joefitzgerald/gofmt#3]
Hi,

When a file exceeds the viewport and I save a file the code blinks (redrawn maybe?):
![out](https://cloud.githubusercontent.com/assets/671040/13891311/a62a821e-ed50-11e5-9a90-2e001c967365.gif)

When I disable gofmt package the issue is gone.
There is no issue when the code does not exceed the viewport meaning there is not enough code to be able to scroll down.
Everything worked great before the upgrade to 4.x.

I'm using:
- go 1.6
- gofmt 1.0.3
- go-plus 4.0.1
- atom 1.6.0
- environment 1.1.1
- OS: osx el capitan

Thanks.

**Comment by joefitzgerald** [comment]
Acknowledged. In an attempt to allow `gofmt` / `goimports` / `goreturns` to be run against unsaved buffers (again, without saving the result), I think I've exposed an issue in atom's grammar parsing as well as causing an issue with undo behavior (i.e. multiple ctrl-z / cmd-z's are required to go backwards).

**Comment by joefitzgerald** [comment]
Please update to `v1.0.4` and let me know if you are still experiencing the issue.

**Comment by celrenheit** [comment]
This solved the issue. Thanks.
