### ISSUE TITLE
goimports doesnt work with gofmt package

### ISSUE THREAD

**Issue by rvzanten** [joefitzgerald/gofmt#30]
I have no errors in my console of Atom and of course goimports located in my $GOPATH/bin folder.
It just won't import anything. All the other packages that come with Go-plus work though.

Running Atom 1.8 here.

Thanks in advance.

**Comment by joefitzgerald** [comment]
Looks like you resolved the issue. What was root cause?

**Comment by rvzanten** [comment]
Well i guess it wasnt a goimports problem. I messaged you on gitter about
this.

2016-07-08 13:53 GMT+02:00 Joe Fitzgerald notifications@github.com:
