### ISSUE TITLE
Add An Option To Exclude Any .go File Contained In A vendor Folder When Formatting On Save

### ISSUE THREAD

**Issue by wchrisjohnson** [joefitzgerald/gofmt#44]
I need to be able to configure the plugin in Atom to NOT update the packages in my vendor folder. How would I do that?

**Comment by joefitzgerald** [comment]
Don't open a file in your vendor folder and then save it. So long as you don't save the file, it won't be formatted.

I suppose we could add an option to not format anything that has `vendor` as a component of the path, but I'd want to leave it disabled by default, as some people may actually want to mutate a file in the vendor directory and have it formatted.

Is the issue that goimports is losing its mind over the imports?

**Comment by wchrisjohnson** [comment]
We are seeing issues with dependencies stored in the vendor folder stripped of git artifacts being updated for some unknown reason. https://github.com/Masterminds/glide/issues/398#issuecomment-239679467  I know that I have the go tools/plugins enabled in Atom (they are awesome!) and am concerned I am inadvertently updating vendored packages.

**Comment by joefitzgerald** [comment]
If you have autosave enabled or if you utilize `File` > `Save All`, and you happen to open files in the vendor folder, it's conceivable they could be manipulated by `goimports` or `gofmt` (whichever one you have configured)

**Comment by wchrisjohnson** [comment]
That makes sense. I would prefer that my tooling NEVER make these sorts of updates for me. I still believe that it would be super helpful if there was a flag I could set to always exclude the vendor folder.

**Comment by joefitzgerald** [comment]
You can turn off format on save in `gofmt` package preferences. Then you can invoke `gofmt` / `goimports` directly on open files via atom commands (`CMD-SHIFT-P`, then `golang: goimports` or `golang: gofmt`).

Open to a pull request to exclude the vendor folder when formatting on save, if you're interested in contributing?
