### ISSUE TITLE
Don't unfold code when running gofmt

### ISSUE THREAD

**Issue by otm** [joefitzgerald/gofmt#5]
After upgrading to go-plus 4 and the new gofmt atom package the code is unfolded when gofmt is run.

Reproduce:
Run "Editor: Fold All"
Run "Golang: Gofmt"

Expected behavior:
The code stays folded.

Actual behavior:
All code is unfolded.

**Comment by joefitzgerald** [comment]
Please update to `v1.0.4` and let me know if you are still experiencing the issue.

**Comment by otm** [comment]
Works fine after upgrade to v1.0.4 and restart of Atom.

Thanks for a great Atom plugin, and such quick fix. Looking forward to see something like https://github.com/joefitzgerald/go-plus/issues/190 to really take advantage of the type system.
