### ISSUE TITLE
Enable / Disable OnSave, OnDemand format tool

### ISSUE THREAD

**Issue by yesnault** [joefitzgerald/gofmt#6]
Hi

(thank you for all the tools to go around atom!)

Is it possible to add option to enable / disable each tools (gofmt, goimports, goreturns) on save and on demand ?
goimports and goreturns can be very very slow, it would be ideal to disable them on save action, but you can run them with Ctrl+P cmd.

I have to remove them on formatter.js, to avoid waiting 3 to 5 seconds before atom wakes at each save.

Thks a lot.

**Comment by joefitzgerald** [comment]
This is already possible. Go to `Atom` > `Preferences` > `Paxkages` > `gofmt` > `Settings` and disable format on save. The commands can be accessed via cmd-shift-p (OS X, use Linux or Windows equivalent of on those platforms) and you can type `golang:gofmt` / `golang:goimports` / `golang:goreturns` - you'll also see their keyboard shortcuts at that time.

**Comment by yesnault** [comment]
Hum, yes, sorry. A fresh install of all plugins give me this option (or I've not seen it before). Thanks a lot !
