### ISSUE TITLE
gofmt is invaild

### ISSUE THREAD

**Issue by fengzixu** [joefitzgerald/gofmt#8]
when i create an error in my go source file,  gofmt in atom is invaild. but when i run gofmt in terminal, it is valid

**Comment by joefitzgerald** [comment]
I need more information. What operating system and version? What version of atom and go-plus and gofmt?

**Comment by fengzixu** [comment]
operating system: osx 10.11.3 
atomversion : 1.6.0
go plus: 4.0.1
gofmt: 1.1.3

when i user Format with gofmt, there is no effect.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. [`builder-go`](https://atom.io/packages/builder-go) will now try to compile your source (test or otherwise) and report errors that would prevent formatting from occurring. Could you please retest with the updates applied?

**Comment by joefitzgerald** [comment]
Are you still having this issue?

**Comment by joefitzgerald** [comment]
Closing this issue due to lack of response; but please let me know if you are still having issues and I will reopen it.
