### ISSUE TITLE
gofmt wont report errors working on save

### ISSUE THREAD

**Issue by jmtsantos** [joefitzgerald/gofmt#9]
Recently, somewhere between an atom update and some package updates gofmt stopped working, i can cause an error on my code, atom wont report a thing while on the terminal gofmt will correctly point the error out. Yet oddly enough it does format the code
Its somewhat similar with #8 

Im on linux with go1.6 running atom 1.6.0 with the following go related plugins

autocomplete-go 1.0.4
enviroment 1.2.0
go-config 1.1.2
go-get 1.0.1
go-plus 4.0.1
go-rename 0.3.0
gofmt 1.1.3
gorename 1.0.0
linter 1.11.4
navigator-godef 1.0.2
gometalinter-linter 1.0.6

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. [`builder-go`](https://atom.io/packages/builder-go) will now try to compile your source (test or otherwise) and report errors that would prevent formatting from occurring.
